"""WAF 检测引擎 — 指纹识别 + 绕过建议 + 熔断机制"""

import re
import asyncio
from typing import Optional

from ..client import HttpClient

# ============================================================
# WAF 指纹库
# ============================================================
WAF_RULES = [
    {
        "name": "Cloudflare",
        "headers": {"Server": r"cloudflare", "CF-RAY": r".*"},
        "body": r"cloudflare|Cloudflare",
        "bypass": ["尝试直接访问源站 IP", "使用特殊 UA (如 Googlebot)", "使用 Cache 绕过 /cdn-cgi/"],
    },
    {
        "name": "阿里云 WAF",
        "headers": {},
        "body": r"errors\.aliyun\.com|阿里云 Web 应用防火墙|waf\.aliyun",
        "bypass": ["编码绕过、分块传输", "HTTP 参数污染 (HPP)", "使用 WebSocket 绕过"],
    },
    {
        "name": "腾讯云 WAF",
        "headers": {},
        "body": r"tencent\.cloud\.waf|waf\.tencent|腾讯云 Web 应用防火墙",
        "bypass": ["大小写混淆", "双重 URL 编码", "Unicode 归一化"],
    },
    {
        "name": "百度云加速",
        "headers": {"Server": r"yunjiasu|baidu"},
        "body": r"baidu.*waf|百度云加速",
        "bypass": ["尝试绕过 CDN 找源站", "使用 X-Forwarded-For 伪造 IP"],
    },
    {
        "name": "长亭 SafeLine",
        "headers": {},
        "body": r"SafeLine|chaitin|长亭",
        "bypass": ["请求方法转换 (GET↔POST)", "参数变异", "大小写绕过"],
    },
    {
        "name": "安全狗",
        "headers": {},
        "body": r"safedog|安全狗",
        "bypass": ["换行绕过", "注释混淆", "分块传输"],
    },
    {
        "name": "D盾",
        "headers": {},
        "body": r"D\.D\.Waf|D盾",
        "bypass": ["变量覆盖", "二次编码"],
    },
    {
        "name": "ModSecurity",
        "headers": {},
        "body": r"ModSecurity|This error was generated by Mod_Security",
        "bypass": ["CRLF 注入", "协议违规", "请求方法变异"],
    },
    {
        "name": "AWS WAF",
        "headers": {},
        "body": r"AWS WAF|awswaf|waf-",
        "bypass": ["使用 AWS 签名版本 4", "调整请求速率"],
    },
    {
        "name": "CloudFront",
        "headers": {"Server": r"CloudFront|cloudfront|Cloudfront", "X-Cache": r".*"},
        "body": r"",
        "bypass": ["直接访问源站 IP", "Host 头劫持"],
    },
    {
        "name": "F5 BIG-IP ASM",
        "headers": {},
        "body": r"BIG-IP|F5",
        "bypass": ["请求方法变异", "参数污染"],
    },
    {
        "name": "Akamai",
        "headers": {"Server": r"AkamaiGHost"},
        "body": r"akamai",
        "bypass": ["使用真实浏览器指纹", "降低请求速率", "使用住宅代理"],
    },
    {
        "name": "360 主机卫士",
        "headers": {},
        "body": r"360wzws|360 Web Application Firewall",
        "bypass": ["编码绕过", "分块传输"],
    },
    {
        "name": "Sucuri",
        "headers": {},
        "body": r"Sucuri|cloudproxy",
        "bypass": ["使用 CloudProxy 绕过", "直接访问源站"],
    },
]

# WAF 拦截页面特征
BLOCK_PATTERNS = [
    # 状态码
    (403, None, "HTTP 403 禁止访问"),
    (503, None, "HTTP 503 服务不可用"),
    # 响应体关键词
    (None, r"just a moment\.\.\.", "Cloudflare 验证页面"),
    (None, r"检测到异常|您的请求已被拦截|访问被拒绝", "WAF 拦截提示"),
    (None, r"blocked|suspicious|malicious", "WAF 通用拦截"),
    (None, r"please complete the security check", "安全验证页面"),
    (None, r"web application firewall|waf", "WAF 拦截"),
    (None, r"触发了安全策略|安全防护", "中文 WAF 拦截"),
]


async def detect_waf(
    url: str,
    proxy: Optional[str] = None,
    cookie: Optional[str] = None,
    auth_token: Optional[str] = None,
    timeout: int = 10,
) -> dict:
    """
    检测目标 URL 是否在 WAF 后面

    Returns:
        {"detected": bool, "name": str, "confidence": str, "bypass": list, "raw": dict}
    """
    result = {
        "detected": False,
        "name": "",
        "confidence": "none",
        "bypass": [],
        "raw": {},
    }

    client = HttpClient(timeout=timeout, proxy=proxy, cookie=cookie, auth_token=auth_token)

    try:
        resp = await client.get(url)
        headers = dict(resp.headers)
        body = resp.text

        for waf in WAF_RULES:
            matched = False
            # Header 匹配
            for hdr, pattern in waf.get("headers", {}).items():
                val = headers.get(hdr, "")
                if re.search(pattern, val, re.IGNORECASE):
                    matched = True
                    break
            # Body 匹配
            body_pat = waf.get("body", "")
            if body_pat and re.search(body_pat, body, re.IGNORECASE):
                matched = True
            if matched:
                result["detected"] = True
                result["name"] = waf["name"]
                result["confidence"] = "high"
                result["bypass"] = waf.get("bypass", [])
                result["raw"] = {
                    "status": resp.status_code,
                    "server": headers.get("Server", ""),
                    "cf_ray": headers.get("CF-RAY", ""),
                }
                return result

        # 间接检测：415/503 等状态码
        if resp.status_code in (403, 503, 429):
            result["detected"] = True
            result["name"] = f"疑似 WAF (HTTP {resp.status_code})"
            result["confidence"] = "medium"
            result["bypass"] = ["降低请求速率", "轮换 User-Agent", "使用代理池"]

    except Exception as e:
        result["raw"]["error"] = str(e)

    return result


async def check_blocked(
    url: str,
    proxy: Optional[str] = None,
    cookie: Optional[str] = None,
    auth_token: Optional[str] = None,
    timeout: int = 10,
) -> dict:
    """
    检查请求是否被 WAF 拦截

    Returns:
        {"blocked": bool, "reason": str, "status": int}
    """
    client = HttpClient(timeout=timeout, proxy=proxy, cookie=cookie, auth_token=auth_token)
    try:
        resp = await client.get(url)
        status = resp.status_code
        body = resp.text

        for status_code, body_pat, reason in BLOCK_PATTERNS:
            if status_code and status == status_code:
                # 如果还有 body 条件，需要进一步检查
                if body_pat and re.search(body_pat, body, re.IGNORECASE):
                    return {"blocked": True, "reason": reason, "status": status}
                if not body_pat:
                    return {"blocked": True, "reason": reason, "status": status}

            if body_pat and re.search(body_pat, body, re.IGNORECASE):
                return {"blocked": True, "reason": reason, "status": status}

        return {"blocked": False, "reason": "", "status": status}
    except Exception as e:
        return {"blocked": False, "reason": f"请求异常: {e}", "status": 0}


class WafCircuitBreaker:
    """WAF 熔断器 — 追踪拦截次数，自动熔断"""

    def __init__(self, max_retries: int = 3):
        self.max_retries = max_retries
        self.block_count = 0
        self.is_open = False
        self.waf_name = ""

    async def check(self, url: str, **kwargs) -> dict:
        """检查一次请求是否被拦截，更新熔断状态"""
        client = HttpClient(timeout=10, **{k: v for k, v in kwargs.items() if v})
        try:
            resp = await client.get(url)
            result = await check_blocked(url, **kwargs)
            if result.get("blocked"):
                self.block_count += 1
                if self.block_count >= self.max_retries:
                    self.is_open = True
                    return {"blocked": True, "tripped": True,
                            "reason": f"连续 {self.block_count} 次被拦截，熔断触发",
                            "status": result.get("status", 0)}
                return {"blocked": True, "tripped": False,
                        "reason": result.get("reason", "被拦截"),
                        "count": self.block_count, "status": result.get("status", 0)}
            # 请求成功，重置计数
            self.block_count = 0
            return {"blocked": False, "tripped": False, "status": resp.status_code}
        except Exception as e:
            return {"blocked": False, "tripped": False, "status": 0, "error": str(e)}

    def reset(self):
        self.block_count = 0
        self.is_open = False


async def waf_precheck(
    url: str,
    waf_mode: str = "safe",
    request_delay: float = 0.5,
    proxy: Optional[str] = None,
    cookie: Optional[str] = None,
    auth_token: Optional[str] = None,
) -> dict:
    """
    WAF 预检 — 被各扫描工具在开始时调用

    Returns:
        {"waf_detected": bool, "waf_name": str, "delay": float, "suggestions": list}
    """
    result = {"waf_detected": False, "waf_name": "", "delay": request_delay, "suggestions": []}

    if waf_mode == "off":
        return result

    waf = await detect_waf(url, proxy=proxy, cookie=cookie, auth_token=auth_token, timeout=8)

    if waf["detected"]:
        result["waf_detected"] = True
        result["waf_name"] = waf["name"]
        # Auto slow down
        if request_delay == 0.5:
            result["delay"] = 3.0
        else:
            result["delay"] = max(request_delay, 2.0)
        result["suggestions"] = waf.get("bypass", [])
    else:
        result["delay"] = request_delay

    return result
